language: java
jdk: 
  - oraclejdk8
  - openjdk8
cache:
  directories: ./lib
before_install:
  - wget -O ivy.zip http://mirrors.ibiblio.org/apache//ant/ivy/2.4.0/apache-ivy-2.4.0-bin.zip
  - unzip ivy.zip
  - wget -O tomcat.zip http://mirrors.ibiblio.org/apache/tomcat/tomcat-8/v8.5.38/bin/apache-tomcat-8.5.38.zip
  - unzip tomcat.zip
install:
  - mv ./apache-tomcat-8.5.38 ./tomcat
  - chmod 555 ./tomcat/bin/catalina.sh
  #- npm install
  - ant resolve -lib ./apache-ivy-2.4.0
before_script: ./tomcat/bin/catalina.sh start
script: ant test -Dj2ee.server.home=./tomcat
after_script: ./tomcat/bin/catalina.sh stop
