dist: bionic
language: java
cache:
  directories: ./lib
addons:
  apt:
    packages:
      - ant
      - ant-optional
      - ivy
      - tomcat8
before_install: sudo ln -sfv /usr/share/java/* $CATALINA_HOME/lib/* /usr/share/ant/lib
install: ant resolve
before_script:
  - sudo ln -sfv /var/lib/tomcat8/conf /var/lib/tomcat8/logs $CATALINA_HOME
  - sudo -u tomcat8 $CATALINA_HOME/bin/catalina.sh start
script: ant test
after_script: sudo -u tomcat8 $CATALINA_HOME/bin/catalina.sh stop
