language: java
jdk: 
  - oraclejdk8
  - openjdk8
cache:
  directories: ./lib
before_install:
  - wget https://archive.apache.org/dist/ant/ivy/2.5.0-rc1/apache-ivy-2.5.0-rc1-bin.tar.gz
  - tar -xf apache-ivy-2.5.0-rc1-bin.tar.gz
  - wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz
  - tar -xf apache-tomcat-8.5.40.tar.gz
install:
  - mv ./apache-tomcat-8.5.40 ./tomcat
  - chmod 555 ./tomcat/bin/catalina.sh
  #- npm install
  - ant resolve -lib ./apache-ivy-2.5.0-rc1
before_script: ./tomcat/bin/catalina.sh start
script: ant test -Dj2ee.server.home=./tomcat
after_script: ./tomcat/bin/catalina.sh stop
